In [2]:
import csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import ot
import ot.plot
import pickle
import os
import re

In [4]:
def extract_six_digit_date(string):
    # Use expression in SummaryDF to extract the 6 digit date
    # since the 6digit date is how our folders are named
    match = re.search(r'(\d{1,2})/(\d{1,2})/(\d{4})', string)
    
    if match:
        # Extract the month, day, and year
        month = match.group(1)
        day = match.group(2)
        year = match.group(3)[-2:]  # Take the last two digits of the year
        
        # Format the date as MMDDYY
        six_digit_date = "{:02}{:02}{}".format(int(month), int(day), year)
        
        return six_digit_date
    
    return None

In [5]:
SummaryDF = pd.read_csv ('C:/Users/nasha/OneDrive - Florida State University/temp_files_extraneous/Summary_dataset.csv',
                         usecols= ['Mouse','Date Exp'])
SummaryDF = SummaryDF.drop([39,40,41])
    # these three are empty rows that show up in the .csv for some reason. let's just delete.

DateFolder = []
for row in range(len(SummaryDF)):
    DateFolder.append(extract_six_digit_date(SummaryDF.iloc[row,1]))
SummaryDF['DateFolder'] = DateFolder
SummaryDF.drop(SummaryDF.tail(1).index, inplace=True)
# dropping last row bc it describes information that comes from a taste trial
# if we want to look at that, we can open it seperately.
# I don't want to put it in this .pickle file
SummaryDF

    Mouse    Date Exp DateFolder
0   CB279  12/16/2021     121621
1   CB279  12/14/2021     121421
2   CB279  12/20/2021     122021
3   CB278  12/15/2021     121521
4   CB278  12/17/2021     121721
5   CB278  12/19/2021     121921
6   CB295    4/2/2022     040222
7   CB295    4/6/2022     040622
8   CB295   3/30/2022     033022
9   CB293    4/2/2022     040222
10  CB293    4/4/2022     040422
11  CB293    4/6/2022     040622
12  CB300    6/9/2022     060922
13  CB300   6/17/2022     061722
14  CB300   6/20/2022     062022
15  CB301    7/3/2022     070322
16  CB301   6/24/2022     062422
17  CB301   6/27/2022     062722
18  CB311   8/10/2022     081022
19  CB311   8/12/2022     081222
20  CB311   8/15/2022     081522
21  CB312   8/10/2022     081022
22  CB312   8/15/2022     081522
23  CB312   8/12/2022     081222
24  CB313   8/12/2022     081222
25  CB313   8/15/2022     081522
26  CB313   8/17/2022     081722
27  CB280  12/17/2021     121721
28  CB280  12/15/2021     121521
29  CB316   10/4/2022     100422
30  CB321  11/30/2022     113022
31  CB289    4/4/2022     040422
32  CB305   6/24/2022     062422
33  CB303   6/17/2022     061722
34  CB303   6/20/2022     062022
35  CB303   6/15/2022     061522
36  CB317   11/8/2022     110822
37  CB317  11/10/2022     111022

In [6]:
path = 'C:/Users/nasha/OneDrive - Florida State University/Temperature session'

In [8]:
NeuronDF = pd.read_pickle(f'{path}/NeuronDF.pickle')

In [9]:
NeuronDF

,Recording Type,MouseID,Date,NeuronID,Taste,Neuron,Trial,-2000,-1999,-1998,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,Neuron,CB279,121621,SU_20,0,0,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Neuron,CB279,121621,SU_44,0,1,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,Neuron,CB279,121621,SU_48,0,2,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Neuron,CB279,121621,SU_51,0,3,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Neuron,CB279,121621,SU_54,0,4,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34875,Neuron,CB317,111022,SU_68,2,428,29,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34876,Neuron,CB317,111022,SU_74,2,429,29,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34877,Neuron,CB317,111022,SU_82,2,430,29,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34878,Neuron,CB317,111022,SU_89,2,431,29,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34879,Neuron,CB317,111022,SU_94,2,432,29,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
with open(f'{path}/{SummaryDF.iloc[0,0]}/{SummaryDF.iloc[0,2]}/SU_Analysis/AllN.pickle', 'rb') as df:
    NDF = pickle.load(df)

# this trial is from the lab's analysis: 
# index of 'trial' changes bc they dropped the first trial from this neuron
NDF_test = NDF[(NDF['Taste'] == 0) & (NDF['Trial'] == 9)
                    & (NDF['n_ID'] == 'SU_20.csv')]

# this trial is from our DF we created:
    # checks that we can open the pickle file and that the trial matches!
Test_NeuronDF = NeuronDF[(NeuronDF['Taste'] == 0) & (NeuronDF['Trial'] == 10)
                         & (NeuronDF['NeuronID'] == 'SU_20') 
                         & (NeuronDF['MouseID'] == SummaryDF.iloc[0,0])]